### ISSUE TITLE
No taps ataa on Saturday

### ISSUE THREAD

**Issue by alibrightman** [ColinWaddell/CWDC_Flask#1]
Friday 19/3/21: Taps are neither on or off tomorrow, as the forecast only shows Today, Sunday, Monday, Tuesday, Wednesday and Thursday.
![image](https://user-images.githubusercontent.com/13614196/111820289-38f82780-88d9-11eb-9862-f1a4d8510c71.png)

**Comment by alibrightman** [comment]
Love your site, by the way!

**Comment by ColinWaddell** [comment]
Totally right. I'll have a gander this week. Cheers!

**Comment by ColinWaddell** [comment]
Sorted
